---
services:
  traefik:
    container_name: 'traefik'
    image: 'docker.io/traefik:3.5.0'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    command:
      - --global.checkNewVersion=true
      - --global.sendAnonymousUsage=false
      - --api=true
      - --api.insecure=false
      - --api.dashboard=true
      - --ping=true
      - --serversTransport.insecureSkipVerify=true
      - --log=true
      - --log.level=INFO
      - --accessLog=true
      - --accessLog.filePath=/traefik.log
      - --accessLog.bufferingSize=100
      - --accessLog.filters.statusCodes=400-499
      - --providers.file.directory=/rules
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --entryPoints.http.address=:8081
      - --entrypoints.http.http.redirections.entryPoint.to=https
      - --entrypoints.http.http.redirections.entryPoint.scheme=https
      - --entryPoints.https.address=:8443
      - --entrypoints.https.http3
      - --entrypoints.https.http3.advertisedPort=8443
      - --entrypoints.https.forwardedHeaders.trustedIPs=173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/12,172.64.0.0/13,131.0.72.0/22
      - --entrypoints.https.http.middlewares=chain-authelia@file
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - '${SECURITYOPS}:${SECURITYOPSSET}'
    ports:
      - target: 8081
        published: 8081
        protocol: tcp
        mode: host
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8082
        protocol: tcp
        mode: host
    volumes:
      - '${APPFOLDER}/traefik/rules:/rules:rw'
      - '${APPFOLDER}/traefik/certs:/tmp/certs:rw'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '${APPFOLDER}/traefik/acme/acme.json:/acme.json:rw'
      - '${APPFOLDER}/traefik/traefik.log:/traefik.log:rw'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    labels:
      - 'dockupdater.enable=true'
      - 'traefik.enable=true'
      - 'traefik.http.routers.traefik-rtr.entrypoints=https'
      - 'traefik.http.routers.traefik-rtr.rule=Host(`traefik.${DOMAIN}`)'
      - 'traefik.http.routers.traefik-rtr.tls=true'
      - 'traefik.http.routers.traefik-rtr.service=api@internal'
  authelia:
    container_name: 'authelia'
    image: 'docker.io/authelia/authelia:4.38.17'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      - traefik
    networks:
      - ${DOCKERNETWORK}
    volumes:
      - '${APPFOLDER}/authelia:/config:rw'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    labels:
      - 'traefik.enable=true'
      - 'dockupdater.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.authelia-rtr.entrypoints=https'
      - 'traefik.http.routers.authelia-rtr.rule=Host(`authelia.${DOMAIN}`)'
      - 'traefik.http.routers.authelia-rtr.tls=true'
      - 'traefik.http.routers.authelia-rtr.service=authelia-svc'
      - 'traefik.http.services.authelia-svc.loadbalancer.server.port=9091'
networks:
  proxy:
    driver: bridge
