services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - ALLOW_SIGNUP=true
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
    ports:
      - "9925:9000"
    volumes:
      - ./data:/app/data
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
