---
services:
  qbittorrent:
    hostname: "qbittorrent"
    container_name: "qbittorrent"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "WEBUI_PORT=8082"
      - "DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent|ghcr.io/smashingtags/homelabarr-mod-qbittorrent:v1.0.0"
      - "TP_THEME=${QBITORRENTTHEME}"
    image: "${QBITORRENTIMAGE}"
    restart: "${RESTARTAPP}"
    ports:
      - "8082:8082"  # Changed from 8080 to avoid conflicts
      - "7889:7889"  # DHT port
    networks:
      - homelabarr-cli-local
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/qbittorrent:/config:rw"
      - "unionfs:/mnt"
    labels:
      - "dockupdater.enable=true"

      # HomelabARR CLI - Traefik Configuration
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent-local-template.entrypoints=websecure"
      - "traefik.http.routers.qbittorrent-local-template.rule=Host(`qbittorrent-local-template.${DOMAIN}`)"
      - "traefik.http.routers.qbittorrent-local-template.tls=true"
      - "traefik.http.routers.qbittorrent-local-template.tls.certresolver=cfdns"
      - "traefik.http.routers.qbittorrent-local-template.middlewares=authelia@docker"
      - "traefik.http.services.qbittorrent-local-template.loadbalancer.server.port=${QBITTORRENT-LOCAL-TEMPLATE_PORT}"
networks:
  homelabarr-cli-local:
    driver: bridge

volumes:
  unionfs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt
