---
services:
  radarr:
    hostname: "radarr"
    container_name: "radarr"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr|ghcr.io/smashingtags/homelabarr-mod-healthcheck:v1.0.0"
      - "TP_THEME=${RADARRTHEME}"
    image: "${RADARRIMAGE}"
    restart: "${RESTARTAPP}"
    ports:
      - "7878:7878"
    networks:
      - bridge
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/radarr:/config:rw"
      - "unionfs:/mnt"
    labels:
      - "dockupdater.enable=true"
    ports:
      - "7878:7878"
networks:
  bridge:
    driver: bridge
    driver: bridge
volumes:
  unionfs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt
