---
services:
  sabnzbd:
    hostname: "sabnzbd"
    container_name: "sabnzbd"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sabnzbd"
      - "TP_THEME=${SABNZBDTHEME}"
    image: "${SABNZBDIMAGE}"
    restart: "${RESTARTAPP}"
    ports:
      - "8085:8080"
    networks:
      - homelabarr-cli-local
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/sabnzbd:/config:rw"
      - "unionfs:/mnt"
    labels:
      - "dockupdater.enable=true"

      # HomelabARR CLI - Traefik Configuration
      - "traefik.enable=true"
      - "traefik.http.routers.sabnzbd-local-template.entrypoints=websecure"
      - "traefik.http.routers.sabnzbd-local-template.rule=Host(`sabnzbd-local-template.${DOMAIN}`)"
      - "traefik.http.routers.sabnzbd-local-template.tls=true"
      - "traefik.http.routers.sabnzbd-local-template.tls.certresolver=cfdns"
      - "traefik.http.routers.sabnzbd-local-template.middlewares=authelia@docker"
      - "traefik.http.services.sabnzbd-local-template.loadbalancer.server.port=${SABNZBD-LOCAL-TEMPLATE_PORT}"
networks:
  homelabarr-cli-local:
    driver: bridge

volumes:
  unionfs:
    driver: local
