---
version: "3"
services:
  HomelabarrCli:
    hostname: "HomelabarrCli"
    container_name: "HomelabarrCli"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "ghcr.io/homelabarr/docker-HomelabarrCli:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/opt/homelabarr-cli:/opt/homelabarr-cli"
    labels:
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true
