---
services:
  rsnapshot:
    hostname: "rsnapshot"
    container_name: "rsnapshot"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "lscr.io/linuxserver/rsnapshot:version-3.1.1"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    volumes:
      - "${APPFOLDER}/rsnapshot:/config:rw"
      - "unionfs/snapshots:/data"
      - "/etc/locatime:/etc/localtime:ro"
    labels:
      - "dockupdater.enable=true"
volumes:
  unionfs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt
