---
name: "Renovate"

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: "false"
        required: false
      logLevel:
        description: Log-Level
        default: debug
        required: false
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json5
      - .github/renovate/**.json5

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate.json5
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Override default config from dispatch variables
        shell: bash
        run: |
          echo "RENOVATE_DRY_RUN=${{ github.event.inputs.dryRun || env.RENOVATE_DRY_RUN }}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${{ github.event.inputs.logLevel || env.LOG_LEVEL }}" >> "${GITHUB_ENV}"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        run: npx renovate
        env:
          RENOVATE_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
